class Commands:
    LEECH = "leech@TorrentGenerator_Bot"
    PURGE = "purge@TorrentGenerator_Bot"
    PAUSEALL = "pauseall@TorrentGenerator_Bot"
    RESUMEALL = "resumeall@TorrentGenerator_Bot"
    STATUS = "status@TorrentGenerator_Bot"
    SETTINGS = "settings@TorrentGenerator_Bot"
    EXEC = "exec@TorrentGenerator_Bot"
    UPLOAD = "upload@TorrentGenerator_Bot"
    YTDL = "ytdl@TorrentGenerator_Bot"
    PYTDL = "pytdl@TorrentGenerator_Bot"
    ABOUT = "about@TorrentGenerator_Bot"
    GETLOGS = "getlogs@TorrentGenerator_Bot"
    SERVER = "server@TorrentGenerator_Bot"
    USERSETTINGS = "usetting@TorrentGenerator_Bot"
    INSTADL = "instadl@TorrentGenerator_Bot"
